"""empty message

Revision ID: 60e209b786a5
Revises: 
Create Date: 2021-03-22 10:56:14.662436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60e209b786a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('all_news',
    sa.Column('id', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('email_hash', sa.String(length=128), nullable=True),
    sa.Column('email_contact', sa.String(length=128), nullable=True),
    sa.Column('group', sa.Integer(), nullable=True),
    sa.Column('first_login', sa.DateTime(), nullable=True),
    sa.Column('last_visit', sa.DateTime(), nullable=True),
    sa.Column('phase_completed', sa.Integer(), nullable=True),
    sa.Column('fake', sa.Integer(), nullable=True),
    sa.Column('panel_id', sa.String(length=128), nullable=True),
    sa.Column('activated', sa.Integer(), nullable=True),
    sa.Column('reminder_sent', sa.Integer(), nullable=True),
    sa.Column('sum_logins', sa.Integer(), nullable=True),
    sa.Column('sum_ratings', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('sum_invites', sa.Integer(), nullable=True),
    sa.Column('sum_stories', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_first_login'), 'user', ['first_login'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic1', sa.Integer(), nullable=True),
    sa.Column('topic2', sa.Integer(), nullable=True),
    sa.Column('topic3', sa.Integer(), nullable=True),
    sa.Column('topic4', sa.Integer(), nullable=True),
    sa.Column('topic5', sa.Integer(), nullable=True),
    sa.Column('topic6', sa.Integer(), nullable=True),
    sa.Column('topic7', sa.Integer(), nullable=True),
    sa.Column('topic8', sa.Integer(), nullable=True),
    sa.Column('topic9', sa.Integer(), nullable=True),
    sa.Column('topic10', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_timestamp'), 'category', ['timestamp'], unique=False)
    op.create_table('diversity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diversity', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('real', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diversity_timestamp'), 'diversity', ['timestamp'], unique=False)
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('elasticsearch', sa.String(length=500), nullable=True),
    sa.Column('recommended', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_timestamp'), 'news', ['timestamp'], unique=False)
    op.create_table('news_sel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.String(length=500), nullable=True),
    sa.Column('starttime', sa.DateTime(), nullable=True),
    sa.Column('endtime', sa.DateTime(), nullable=True),
    sa.Column('time_spent', sa.Interval(), nullable=True),
    sa.Column('rating', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('rating2', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_sel_endtime'), 'news_sel', ['endtime'], unique=False)
    op.create_index(op.f('ix_news_sel_starttime'), 'news_sel', ['starttime'], unique=False)
    op.create_table('num_recommended',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num_recommended', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('real', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_num_recommended_timestamp'), 'num_recommended', ['timestamp'], unique=False)
    op.create_table('points_logins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('points_logins', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_points_logins_timestamp'), 'points_logins', ['timestamp'], unique=False)
    op.create_table('points_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('points_ratings', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_points_ratings_timestamp'), 'points_ratings', ['timestamp'], unique=False)
    op.create_table('points_stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('points_stories', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_points_stories_timestamp'), 'points_stories', ['timestamp'], unique=False)
    op.create_table('show_again',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('show_again', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_show_again_timestamp'), 'show_again', ['timestamp'], unique=False)
    op.create_table('similarities',
    sa.Column('sim_id', sa.Integer(), nullable=False),
    sa.Column('id_old', sa.Integer(), nullable=True),
    sa.Column('id_new', sa.String(length=500), nullable=True),
    sa.Column('similarity', sa.Numeric(precision=10, scale=9), nullable=True),
    sa.ForeignKeyConstraint(['id_new'], ['all_news.id'], ),
    sa.ForeignKeyConstraint(['id_old'], ['news_sel.id'], ),
    sa.PrimaryKeyConstraint('sim_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('similarities')
    op.drop_index(op.f('ix_show_again_timestamp'), table_name='show_again')
    op.drop_table('show_again')
    op.drop_index(op.f('ix_points_stories_timestamp'), table_name='points_stories')
    op.drop_table('points_stories')
    op.drop_index(op.f('ix_points_ratings_timestamp'), table_name='points_ratings')
    op.drop_table('points_ratings')
    op.drop_index(op.f('ix_points_logins_timestamp'), table_name='points_logins')
    op.drop_table('points_logins')
    op.drop_index(op.f('ix_num_recommended_timestamp'), table_name='num_recommended')
    op.drop_table('num_recommended')
    op.drop_index(op.f('ix_news_sel_starttime'), table_name='news_sel')
    op.drop_index(op.f('ix_news_sel_endtime'), table_name='news_sel')
    op.drop_table('news_sel')
    op.drop_index(op.f('ix_news_timestamp'), table_name='news')
    op.drop_table('news')
    op.drop_index(op.f('ix_diversity_timestamp'), table_name='diversity')
    op.drop_table('diversity')
    op.drop_index(op.f('ix_category_timestamp'), table_name='category')
    op.drop_table('category')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_first_login'), table_name='user')
    op.drop_table('user')
    op.drop_table('all_news')
    # ### end Alembic commands ###
